[package]
name = "lean-liquid"
version = "0.1"
lean_version = "leanprover-community/lean:3.28.0"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "c65146d6508bc4b7b7f796c7c789cd05f06c20ec"}
lean-gptf = {git = "https://github.com/jesse-michael-han/lean-gptf", rev = "3e20785d65604744e9e2dc9d710a695a7355fd2c"}
