name: update nolints

on:
  workflow_dispatch: ~
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    name: Build, lint and update nolints
    runs-on: ubuntu-latest
    env:
      # number of commits to check for olean cache
      GIT_HISTORY_DEPTH: 20
    steps:
      - uses: actions/checkout@v2
        with:
          repository: leanprover-community/mathlib
          fetch-depth: ${{ env.GIT_HISTORY_DEPTH }}

      - name: install elan
        run: |
          set -o pipefail
          curl https://raw.githubusercontent.com/Kha/elan/master/elan-init.sh -sSf | sh -s -- --default-toolchain none -y
          ~/.elan/bin/lean --version
          echo "$HOME/.elan/bin" >> $GITHUB_PATH
          echo "name=short_lean_version::$(~/.elan/bin/lean --run scripts/lean_version.lean)" >> $GITHUB_ENV

      - name: install Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: try to find olean cache
        continue-on-error: true
        run: ./scripts/fetch_olean_cache.sh

      - name: leanpkg build
        id: build
        run: |
          leanpkg configure
          lean --json --make src | python scripts/detect_errors.py

      - name: lint
        run: |
          ./scripts/mk_all.sh
          lean --run scripts/lint_lean_liquid.lean
          mv nolints.txt scripts/nolints.txt
          # ./scripts/update-style-exceptions.sh
          git diff

      # TODO can we replace this with the version from upgrade_lean.yml?
      - name: configure git setup
        # We need to use a personal access token here. See the comment in upgrade_lean.yml.
        run: |
          git remote add origin-bot "https://leanprover-community-bot:${{ secrets.PA_TOKEN }}@github.com/leanprover-community/mathlib.git"
          git config user.email "leanprover.community@gmail.com"
          git config user.name "leanprover-community-bot"

          # By default, github actions overrides the credentials used to access any
          # github url so that it uses the github-actions[bot] user.  We want to access
          # github using a different username.
          git config --unset http.https://github.com/.extraheader

      - name: update nolints.txt
        run: ./scripts/update_nolints.sh
        env:
          DEPLOY_GITHUB_TOKEN: ${{ secrets.PA_TOKEN }}
