# Keep `name` in sync with `on.workflow_run.workflows` in `build.yml`.
name: bump lean and dependencies
on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *' # once a day at 2am UTC

jobs:
  upgrade_lean:
    runs-on: ubuntu-latest
    name: Bump lean and dependencies
    steps:
      - name: checkout project
        uses: actions/checkout@v2
      - name: upgrade lean and dependencies
        uses: leanprover-contrib/lean-upgrade-action@master
        with:
          repo: ${{ github.repository }}
          access-token: ${{ secrets.GITHUB_TOKEN }}

# We trigger the build.yml workflow after this workflow runs. See `on.workflow_run` in `build.yml`.
# This updates the lean-3.x branch, uploads oleans, and runs tests, etc. This trigger fires
# regardless of whether or not this succeeds.
#
# TODO figure out what to do if it fails, e.g., it's a no-op.
