# Keep "name" in sync with name in build.on.workflow_run.workflows
name: bump lean and dependencies
on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *' # once a day at 2am UTC

jobs:
  upgrade_lean:
    runs-on: ubuntu-latest
    name: Bump lean and dependencies
    steps:
      - name: Upgrade lean and dependencies
        uses: leanprover-contrib/lean-upgrade-action@master
        with:
          repo: ${{ github.repository }}
          access-token: ${{ secrets.GITHUB_TOKEN }}
